name: gympad
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  http: ^1.4.0
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_analytics: ^12.0.0
  firebase_auth: ^6.0.0
  numberpicker: ^2.1.2
  google_fonts: ^6.1.0
  url_launcher: ^6.2.5
  google_sign_in: ^7.1.1
  dio: ^5.8.0
  logging: ^1.3.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.5
  infinite_listview: ^1.1.0
  flutter_launcher_icons: ^0.14.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_test: ^1.0.1
  just_audio: ^0.10.4
  go_router: ^16.2.1
  v_scroller: 
    path: ../../v_scroller

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

  flutter_lints: ^5.0.0
  test: ^1.25.15
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/mock_data/
    - assets/audio/
    - assets/intro_images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
